"""empty message

Revision ID: 0a88504d939f
Revises: 39536078ee3b
Create Date: 2019-04-25 14:21:10.627044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a88504d939f'
down_revision = '39536078ee3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_log', sa.Column('method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'method')
    # ### end Alembic commands ###
