"""empty message

Revision ID: 159371b77a4d
Revises: 
Create Date: 2019-04-04 12:44:30.186106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159371b77a4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('question_type', sa.BigInteger(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('manually_grading', sa.Boolean(), nullable=True),
    sa.Column('points', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=True),
    sa.Column('max_time', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('role', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates_autorization',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('candidates_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cv', sa.Text(), nullable=True),
    sa.Column('letter_of_recommendation', sa.Text(), nullable=True),
    sa.Column('motivation_letter', sa.Text(), nullable=True),
    sa.Column('passport', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('subscription_email', sa.Text(), nullable=True),
    sa.Column('skype', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates_interview',
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('candidate_id', 'staff_id')
    )
    op.create_table('candidates_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('time_start', sa.Date(), nullable=True),
    sa.Column('time_end', sa.Date(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_tests',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates_answers',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('answer', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('grade', sa.Numeric(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['candidates_submissions.id'], ),
    sa.PrimaryKeyConstraint('submission_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates_answers')
    op.drop_table('staff')
    op.drop_table('questions_tests')
    op.drop_table('candidates_submissions')
    op.drop_table('candidates_status')
    op.drop_table('candidates_interview')
    op.drop_table('candidates_info')
    op.drop_table('candidates_documents')
    op.drop_table('candidates_autorization')
    op.drop_table('users')
    op.drop_table('tests')
    op.drop_table('revoked_tokens')
    op.drop_table('questions')
    # ### end Alembic commands ###
