"""empty message

Revision ID: 39536078ee3b
Revises: b057ccaaa6e7
Create Date: 2019-04-25 14:05:21.216196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39536078ee3b'
down_revision = 'b057ccaaa6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('questions_tests_question_id_fkey', 'questions_tests', type_='foreignkey')
    op.drop_constraint('questions_tests_test_id_fkey', 'questions_tests', type_='foreignkey')
    op.create_foreign_key(None, 'questions_tests', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'questions_tests', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions_tests', type_='foreignkey')
    op.drop_constraint(None, 'questions_tests', type_='foreignkey')
    op.create_foreign_key('questions_tests_test_id_fkey', 'questions_tests', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('questions_tests_question_id_fkey', 'questions_tests', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_table('request_log')
    # ### end Alembic commands ###
