"""empty message

Revision ID: 55710a27f803
Revises: 5b8116918584
Create Date: 2019-04-24 19:31:34.278971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55710a27f803'
down_revision = '5b8116918584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revoked_tokens', 'jti',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.alter_column('revoked_tokens', 'jti',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
