"""empty message

Revision ID: 5b8116918584
Revises: 0b2efa028633
Create Date: 2019-04-21 17:59:42.987706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8116918584'
down_revision = '0b2efa028633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates_submissions', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates_submissions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates_submissions', type_='foreignkey')
    op.drop_column('candidates_submissions', 'test_id')
    # ### end Alembic commands ###
